FROM envoyproxy/envoy-alpine:v1.12.2

RUN export http_proxy=http://115.159.17.125:9443 && export https_proxy=http://115.159.17.125:9443 && apk update && apk add python3 bash
RUN python3 --version && pip3 --version
RUN pip3 install -i https://pypi.douban.com/simple -q Flask==0.11.1 requests==2.18.4
RUN mkdir /code
ADD service.py /code
ADD start_service.sh /usr/local/bin/start_service.sh
RUN chmod u+x /usr/local/bin/start_service.sh
ENTRYPOINT /usr/local/bin/start_service.sh
